export enum NotificationType {
  WORK_ITEM_ASSIGNED = 'WORK_ITEM_ASSIGNED',
  WORK_ITEM_ROLE_CHANGED = 'WORK_ITEM_ROLE_CHANGED',
  WORK_ITEM_UNASSIGNED = 'WORK_ITEM_UNASSIGNED',
  WORK_COMMENT_CREATED = 'WORK_COMMENT_CREATED',
  WORK_COMMENT_MENTION = 'WORK_COMMENT_MENTION',
  WORK_COMMENT_REPLY = 'WORK_COMMENT_REPLY',
  WORK_REVIEW_REQUEST = 'WORK_REVIEW_REQUEST',
  SLA_REMINDER = 'SLA_REMINDER',
}
