export enum WorkPermission {
  WORK_VIEW = 'WORK_VIEW',
  WORK_CREATE = 'WORK_CREATE',
  WORK_UPDATE = 'WORK_UPDATE',
  WORK_DELETE = 'WORK_DELETE',
  WORK_ASSIGNMENT_MANAGE = 'WORK_ASSIGNMENT_MANAGE',
  WORK_ASSIGNMENT_VIEW = 'WORK_ASSIGNMENT_VIEW',
}
