export enum PermissionEnum {
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  TASK_CREATE = 'TASK_CREATE',
  TASK_ASSIGN = 'TASK_ASSIGN',
  TASK_COMPLETE = 'TASK_COMPLETE',
}
