export enum WorkReviewStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  REWORK_REQUIRED = 'REWORK_REQUIRED',
  RESUBMITTED = 'RESUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
