export enum WorkStatus {
  TO_DO = 'TO_DO',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  TEAM_REVIEW = 'TEAM_REVIEW',
  QA_TEST = 'QA_TEST',
  COMPLETED = 'COMPLETED',
  REWORK_REQUIRED = 'REWORK_REQUIRED',
  CANCELLED = 'CANCELLED',
}
